<?php

/**
 * @file
 * Implementation of Roblib search for searching several targets.
 */


/**
 * Implements hook_menu().
 */
function roblib_search_solr_site_menu() {
  $items = array();

  $items['admin/roblib_search/solr_site_search'] = array(
    'title' => 'Roblib Solr Search Target configuration',
    'description' => 'Configuration for the Roblib Solr site search target',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('roblib_search_solr_site_config_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['roblib_search/solr_site/bestbet/%'] = array(
    'title' => 'BestBet',
    'page callback' => 'roblib_search_solr_site_bestbet',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('search roblib solr_site'),
  );

  $items['roblib_search/solr_site/databases/%'] = array(
    'title' => 'solr_site databases',
    'page callback' => 'roblib_search_solr_site_databases',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('search roblib solr_site'),
  );

  $items['roblib_search/solr_site/guides/%'] = array(
    'title' => 'solr_site guides',
    'page callback' => 'roblib_search_solr_site_guides',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('search roblib solr_site'),
  );

  $items['roblib_search/solr_site/results/%'] = array(
    'title' => 'solr_site guides',
    'page callback' => 'roblib_search_solr_site_results',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('search roblib solr_site'),
  );


  return $items;
}

function roblib_search_solr_site_config_form($form, &$form_state) {
  $form['roblib_search_solr_site_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Solr url'),
    '#default_value' => variable_get('roblib_search_solr_site_url', 'http://localhost:8983/solr'),
    '#description' => t('The base Solr URL, for example http://localhost:8983/solr'),
    '#required' => TRUE,
  );
  $form['roblib_search_solr_site_num_results'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of results to return'),
    '#default_value' => variable_get('roblib_search_solr_site_num_results', '5'),
    '#description' => t('The number of results to display in the Bento box'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_permission().
 */
function roblib_search_solr_site_permission() {
  return array(
    'search roblib solr_site' => array(
      'title' => t('Search the solr_site target'),
      'description' => t('Search all Roblib solr_site target. This permission exposes the search blocks and allows you to see search results.'),
    ),
    'administer roblib search_solr_site' => array(
      'title' => t('Administer Roblib Search Evergreen'),
      'description' => t('Administer settings for the Roblib solr_site search client.'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function roblib_search_solr_site_theme() {
  // set path
  $path = drupal_get_path('module', 'roblib_search_solr_site');
  $file = 'theme.inc';

  return array(
    // results page
    'roblib_search_solr_site_bestbet' => array(
      'path' => $path . '/theme',
      'file' => $file,
      'template' => 'roblib-search-solr-site-results',
      'variables' => array('results' => NULL),
    ),
    'roblib_search_solr_site_databases' => array(
      'path' => $path . '/theme',
      'file' => $file,
      'template' => 'roblib-search-solr-site-results',
      'variables' => array('results' => NULL),
    ),
    'roblib_search_solr_site_guides' => array(
      'path' => $path . '/theme',
      'file' => $file,
      'template' => 'roblib-search-solr-site-results',
      'variables' => array('results' => NULL),
    ),
    'roblib_search_solr_site_results' => array(
      'path' => $path . '/theme',
      'file' => $file,
      'template' => 'roblib-search-solr-site-results',
      'variables' => array('results' => NULL),
    ),
  );
}

function roblib_search_solr_site_block_info() {

  $blocks['roblib_search_solr_site_bestbet'] = array(
    // info: The name of the block.
    'info' => t('Roblib Solr Search Best bets'),
    // Block caching options (per role, per user, etc.)
    'cache' => DRUPAL_CACHE_PER_ROLE, // default
  );

  $blocks['roblib_search_solr_site_db'] = array(
    // info: The name of the block.
    'info' => t('Roblib Solr Search Databases Block'),
    // Block caching options (per role, per user, etc.)
    'cache' => DRUPAL_CACHE_PER_ROLE, // default
  );

  $blocks['roblib_search_solr_site_guides'] = array(
    // info: The name of the block.
    'info' => t('Roblib Solr Search Guides Block'),
    // Block caching options (per role, per user, etc.)
    'cache' => DRUPAL_CACHE_PER_ROLE, // default
  );

  $blocks['roblib_search_solr_site_results'] = array(
    // info: The name of the block.
    'info' => t('Roblib Solr Search Results Block'),
    // Block caching options (per role, per user, etc.)
    'cache' => DRUPAL_CACHE_PER_ROLE, // default
  );

  return $blocks;
}

function roblib_search_solr_site_block_view($delta = '') {
  switch ($delta) {
    case 'roblib_search_solr_site_bestbet':
      $block['subject'] = t('Best Bets');
      $block['content'] = theme('roblib_search_solr_site_bestbet', array('results' => NULL));
      break;

    case 'roblib_search_solr_site_db':
      $block['subject'] = t('Databases');
      $block['content'] = theme('roblib_search_solr_site_databases', array('results' => NULL));
      break;

    case 'roblib_search_solr_site_guides':
      $block['subject'] = t('Guides');
      $block['content'] = theme('roblib_search_solr_site_guides', array('results' => NULL));
      break;

    case 'roblib_search_solr_site_results':
      $block['subject'] = t('Library Site');
      $block['content'] = theme('roblib_search_solr_site_results', array('results' => NULL));
      break;
  }
  return $block;
}

function roblib_search_solr_site_results($query) {
  print roblib_search_solr_site_get_results($query, '-bundle:bestbet OR -budle:guide OR -bundle:database');
  exit();
}

function roblib_search_solr_site_bestbet($query) {
  print roblib_search_solr_site_get_results($query, 'bundle:bestbet');
  exit();
}

function roblib_search_solr_site_databases($query) {
  print roblib_search_solr_site_get_results($query, 'bundle:database');
  exit();
}

function roblib_search_solr_site_guides($query) {
  print roblib_search_solr_site_get_results($query, 'bundle:guide');
  exit();
}

/**
 *
 * @param string $query
 * @return string
 *   json
 */
function roblib_search_solr_site_get_results($query = NULL, $type ) {
  $solr_url = variable_get('roblib_search_solr_site_url', 'http://localhost:8983/solr');
  $num_results = variable_get('roblib_search_solr_site_num_results', '5');
  $data = array(
    'q' => $query,
    'fq' => $type,
    'wt' => 'json',
    'rows' => $num_results,
  );
  $url = url($solr_url . '/select', array('query' => $data));

  $results = drupal_http_request($url);
  if ($results->code != '200') {
    return "";
  }
  return $results->data;
}


/**
 * Implements hook_help().
 */
function roblib_search_solr_site_help($path, $arg) {
  switch ($path) {
    case 'admin/help#roblib_search_solr_site':
      return t(
        '<p>
provides a target for the Roblib search module
</p>'
      );
  }
}
